### ISSUE TITLE
App crash on 4.3.0 

### ISSUE THREAD

**Issue by jainharsh96** [sqlcipher/android-database-sqlcipher#492]
### Expected Behavior
App should not crash 
### Actual Behavior
app crash
### Steps to Reproduce
at the time of opening app
SQLCipher version (can be identified by executing `PRAGMA cipher_version;`):

SQLCipher for Android version:
implementation 'net.zetetic:android-database-sqlcipher:4.3.0@aar'
implementation "androidx.sqlite:sqlite:2.0.1"
The app is working fine in version 3.5.9 but when I update to 4.3.0
it is crashing at

SQLiteDatabase.loadLibs(getApplicationContext());

error 

Failed to register native method net.sqlcipher.database.SQLiteQuery.native_fill_window(Lnet/sqlcipher/CursorWindow;IIII)I in /data/app/in.xyz.android-iXul6lzMJAHofEZYxrhuUg==/base.apk!classes3.dex
2020-02-05 11:46:28.314 19196-19196/? A/n.xyz.androi: java_vm_ext.cc:542] JNI DETECTED ERROR IN APPLICATION: JNI FindClass called with pending exception java.lang.NoSuchMethodError: no static or non-static method "Lnet/sqlcipher/database/SQLiteQuery;.native_fill_window(Lnet/sqlcipher/CursorWindow;IIII)I"
2020-02-05 11:46:28.314 19196-19196/? A/n.xyz.androi: java_vm_ext.cc:542]   at java.lang.String java.lang.Runtime.nativeLoad(java.lang.String, java.lang.ClassLoader) (Runtime.java:-2)
2020-02-05 11:46:28.314 19196-19196/? A/n.xyz.androi: java_vm_ext.cc:542]   at void java.lang.Runtime.loadLibrary0(java.lang.ClassLoader, java.lang.String) (Runtime.java:1014)
2020-02-05 11:46:28.314 19196-19196/? A/n.xyz.androi: java_vm_ext.cc:542]   at void java.lang.System.loadLibrary(java.lang.String) (System.java:1669)
2020-02-05 11:46:28.314 19196-19196/? A/n.xyz.androi: java_vm_ext.cc:542]   at void net.sqlcipher.database.SQLiteDatabase$1.loadLibraries(java.lang.String[]) (SQLiteDatabase.java:227)
2020-02-05 11:46:28.314 19196-19196/? A/n.xyz.androi: java_vm_ext.cc:542]   at void net.sqlcipher.database.SQLiteDatabase.loadLibs(android.content.Context, java.io.File, net.sqlcipher.database.SQLiteDatabase$LibraryLoader) (SQLiteDatabase.java:244)
2020-02-05 11:46:28.314 19196-19196/? A/n.xyz.androi: java_vm_ext.cc:542]   at void net.sqlcipher.database.SQLiteDatabase.loadLibs(android.content.Context, java.io.File) (SQLiteDatabase.java:223)
2020-02-05 11:46:28.314 19196-19196/? A/n.xyz.androi: java_vm_ext.cc:542]   at void net.sqlcipher.database.SQLiteDatabase.loadLibs(android.content.Context) (SQLiteDatabase.java:216)

**Comment by theBlbDan** [comment]
Go read the FAQ on upgrading to 4.x from 3.x.

https://discuss.zetetic.net/t/upgrading-to-sqlcipher-4/3283

**Comment by jainharsh96** [comment]
Issue resolved

**Comment by jainharsh96** [comment]
now my encrypted database is working fine in 4.3.0

but now I am not able to open this database in SQLite browser for debugging purposes. The app is working fine
in previous version 3.5.9, database opening in sqlitebrowser.
i am using sqlitebrowser version 3.11.2

Version 3.11.2

Built for x86_64-little_endian-lp64, running on x86_64

Qt Version 5.9.5

SQLCipher Version 3.4.1 (based on SQLite 3.15.2) 

from - http://sqlitebrowser.org

**Comment by developernotes** [comment]
Hi @jainharsh96 

We use GitHub Issues for tracking reports of software defects only. This question is a good fit for the [SQLCipher community discuss site](https://discuss.zetetic.net/c/sqlcipher). You might check out the [DB Browser for SQLite nightly](https://nightlies.sqlitebrowser.org/latest/) as they support the latest major SQLCipher release. Thanks!
